In [2]:
import numpy as np

*ARRAY OPERATION*

Arithmetic operations

In [3]:
# +
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
sum = (arr1 + arr2)
print(sum)

[ 9 23  8 53 12]


In [4]:
# -
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
sub = (arr1 - arr2)
print(sub)

[ -7 -19  -2 -45  -2]


In [5]:
# *
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
mul = (arr1 * arr2)
print(mul)

[  8  42  15 196  35]


In [6]:
# /
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
div = (arr1 / arr2)
print(div)

[0.125      0.0952381  0.6        0.08163265 0.71428571]


In [7]:
# //
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
float_div = (arr1 //   arr2)
print(float_div)

[0 0 0 0 0]


In [8]:
# **
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([8,21,5,49,7])
power = (arr1 ** arr2)
print(power)

[      1 2097152     243       0   78125]


AND MANY MORE OPERATIONS.......

Brodcasting

If you want to simply add mul or wanna do any arithmetic operation on the whole array just do it with array inplace of using a loop

In [9]:
l = [10,20,30,40,50,60,70]
arr3 = np.array(l)
arr3

array([10, 20, 30, 40, 50, 60, 70])

In [10]:
#now i want to add 10 to every element og the arr3 just add it

print(arr3+10)

[20 30 40 50 60 70 80]


In [11]:
arr4 = np.arange(1,26).reshape(5,5)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
mult_brod = arr4 * 10
print(mult_brod)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]


Just Perform any other opertion isng brodcating.....

Deep and shallow copy

In [13]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
slice = a[:5]
print(slice * 10)

[10 20 30 40 50]


In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a[4:6]*10

array([50, 60])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [18]:
matr1= np.array([[1,2] , [3,4]])
matr2= np.array([[5,6] , [7,8]])

In [19]:
# if we do matrix multipication using the arithmetic operation
#that is not how original matrix multipication work

print(matr1 * matr2)

[[ 5 12]
 [21 32]]


In [20]:
# real mat multi. 
# use @
# or np.dot

print(matr1 @ matr2)
print()

np.dot(matr1,matr2)

[[19 22]
 [43 50]]



array([[19, 22],
       [43, 50]])

In [21]:
#transpose
#use.t

matr1_transpose = matr1.T
print(matr1_transpose)

[[1 3]
 [2 4]]


Advance Array Manupilation

Stacking Array

Note: we can't stack the 2d array


There are three types of stacks 
* vertical Stack
* horizontal Stack
* Simple stack

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [23]:
#for vertical stack 
#use .vstack(a,b)

np.vstack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
#for horizontal stack 
#use .hstack(a,b)

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#column stack
# use np.column_stack

np.column_stack((a,b))


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

Split is also two types:
1. is horizontal split
2. is vertical split

In [26]:
c = np.arange(16).reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [27]:
#horizontal split hsplit
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [28]:
#vertical split vsplit
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]