In [9]:
import numpy as np

*Basic Array creation*

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
#list comaring with array
a = [1,2,3,5,"hello"]
a

[1, 2, 3, 5, 'hello']

In [ ]:
# Force integers, floats will be truncated
arr_int = np.array([1, 2.5, 3], dtype=int)
print(arr_int) # Output: [1 2 3] (2.5 is truncated to 2)

# Force strings, numbers will be converted to strings
arr_str = np.array([1, 2, 3, 4.0], dtype=str)
print(arr_str) # Output: ['1' '2' '3' '4.0']

[1 2 3]
['1' '2' '3' '4.0']


In [ ]:
#when we write 2d array using list it will give outout that looks like 1d array
# for eg
l =  [[1,2,3] , [4,5,6] , [7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
#now if we want to print it as a 2d array we use np.array
#for eg l =  [[1,2,3] , [4,5,6] , [7,8,9]]

print(np.array(l))
# this is 2d array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


*Array generation function*

In [ ]:
 #it is just like the range func that we learn in for loop,

arr = np.arange(1,11) #will print array 1 to 10
print(arr)

print(np.arange(1,11,2)) # will print odd no,


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
#now if we want to get  array of zeros

print(np.zeros(6)) 
#output will be in the 1d array

[0. 0. 0. 0. 0. 0.]


In [ ]:
#so for the 2d array of zeros
print(np.zeros((4,8))) # or in simple terms
#arr = np.zeros((6,6))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#just like for zeros array there is also ones array
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
b = np.linspace(1,5,3)
print(b)

a = np.linspace(0,1,100)
a

[1. 3. 5.]


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

*Random Generation Function*

In [ ]:
#to generate a random 1d array
# use random.rand
#if you are using random.rand you will follow normalization 
# it means that random no. will be generated will be between 0 and 1

np.random.rand(10) 

array([0.48300306, 0.12545579, 0.86633962, 0.24590972, 0.79566572,
       0.05151827, 0.19181725, 0.87441841, 0.83568919, 0.3416074 ])

In [ ]:
# and other is standarization,
# random.randn
# it means that random no. will be generated will be between 3 and -3

np.random.randn(10)  

array([ 1.04625363,  0.27735871,  1.11173569, -0.60353206, -1.83894245,
        1.7240598 , -0.50507   , -0.88638292,  1.12712   ,  0.89925846])

In [ ]:
#And if you want to generate an random integer just like we used to do in the python 
# use random.randint(strting value , stoping value , how many numbers to be choosn randomly)


c = np.random.randint(10,20,10)  
print(c)


[18 10 13 13 13 19 12 14 10 10]


In [ ]:
#to choos a random nu. from chice
print(np.random.choice([1,2,3]))

*Array Attributes*


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#shape attribute (remeber: we don't put bracket in the attribute)
#use name.shape

arr.shape

#or for 1d array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.shape)  # Output: (5,)

# output will tell no. of rows and columns

(3, 3)

In [ ]:
#size attribute , it tells how many elements are there in the array
#use name.size

arr.size

9

In [ ]:
#type attribute tell the type of the elements in the array
# use name.dtye

arr.dtype

dtype('int64')

In [ ]:
#Number of Dimensions,  
# For example, a 1D array (vector) has ndim = 1, a 2D array (matrix) has ndim = 2, and so on.

arr_1d = np.array([1, 2, 3])
print(arr_1d.ndim)  # Output: 1

arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.ndim)  # Output: 2

1
2


In [ ]:
#Size of Each Element, This attribute returns the size (in bytes) of each element in the array.
arr_int = np.array([1, 2, 3], dtype=np.int32)
print(arr_int.itemsize) # Output: 4 (for a 32-bit integer)

arr_float = np.array([1.0, 2.0], dtype=np.float64)
print(arr_float.itemsize) # Output: 8 (for a 64-bit float)

4
8


In [ ]:
# Total Bytes Consumed
#this attribute returns the total number of bytes consumed by the array's data. It's equivalent to array.size * array.itemsize

arr = np.array([[1, 2], [3, 4]], dtype=np.int32)
print(arr.nbytes) # Output: 16 (4 elements * 4 bytes/element)

16


In [ ]:
#Transposed Array

arr = np.array([[1, 2], [3, 4]])
print(arr)
# [[1 2]
#  [3 4]]

print(arr.T)
# [[1 3]
#  [2 4]]

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


*Array methods*

In [ ]:
# note in methods we need to use the curve brackets
#array minimum: to find out the element in the array which is minimum 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.min())

#array maximum: to find out the element in the array which is maximum
print(arr.max())


1
9


In [ ]:
#argmax() : to find out the index of the maximum element in the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.argmax())

#argmin() : to find out the index of the minimum element in the array
print(arr.argmin())


8
0


In [ ]:
#suming all the elements in the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.sum())


45


In [ ]:
# summing the column of the matrix
# for that np.sum(arr, axis=0)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.sum(axis=0))

[12 15 18]


In [ ]:
# summing the row of the matrix
# for that np.sum(arr, axis=1)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.sum(axis=1))

[ 6 15 24]


In [ ]:
#mean of the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.mean())

5.0


In [ ]:
# standard deviation of the array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.std())

2.581988897471611


*Reshaping and Resizing*

In [ ]:
#reshape() , if you have 30 elements in 1d array,
#  and now you have to store it in inside an 2d array
# ,so you will use reshape(row,column)

arr1 = np.arange(1,31)
print(f"1d array with elements till 1 to 30: {arr1}")

1d array with elements till 1 to 30: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [ ]:
#now use reshape(r,c)
arr1 = arr1.reshape(5,6)
print(f"2d array with 5 rows and 6 columns:{arr1}")
print()

#now use reshape(r,c)
arr1 = arr1.reshape(6,5)
print(f"2d array with 5 rows and 6 columns:{arr1}")

2d array with 5 rows and 6 columns:[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

2d array with 5 rows and 6 columns:[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
