In [39]:
import numpy as np

*NUMPY INDEXING AND SLICING OF VECTORS*

In [40]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [41]:
arr_slice = arr[3::2]
print(arr_slice)

[14 16 18 20]


*NUMPY INDEXING AND SLICING OF MATRIX*

In [42]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [43]:
print(arr[5,4])
print(arr[:3])


30
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Now if you want to print the matrix of [[2,3],[7,8]],
we will use the slicing.
1. check rows that is 0 to 1
2. check columns that is 1 to 2
3. now use the slicing

In [44]:
slice_mat = arr[0:2 , 1:3]
print(slice_mat)

[[2 3]
 [7 8]]


Now print the matrix of [[19,20],[24,25],[29,30]],

In [45]:
slice_mat2 = arr[3:,3:]
print(slice_mat2)

[[19 20]
 [24 25]
 [29 30]]


now print the column no. 2

In [46]:
col_sl = arr[:,2]
print(col_sl)
#output: [ 3  8 13 18 23 28] after slicing it default make a new array

[ 3  8 13 18 23 28]


*BOOLEAN INDEXING*

For example if you want to print an array with only even int without using the loops than we can use boolean indexing

In [47]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [48]:
bool_index = arr % 2 == 0 
# it will return true at index at which given condition is true
print(bool_index)

[False  True False  True False  True False  True False  True]


In [49]:
arr = arr[bool_index]
# it will make the new array in which the index was true
print(arr)

[12 14 16 18 20]
