In [40]:
import numpy as np


*VALID SUDOKU*

In [41]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [42]:
sum_row = s.sum(axis=1)
# print(sum_row)

#or
b= np.sum(s,axis=1)
# print(sum_row1)
for i in b:
    if i != 45:
        print("Sudoku is not valid!")
else:
    print("for the rows it is valid!")


for the rows it is valid!


In [ ]:
#now we will check for columns
c= np.sum(s,axis=0)
# print(c)
for i in c:
    if i != 45:
        print("Sudoku is not valid!")
else:
    print("for the columns it is valid!")


for the columns it is valid!


we have checked that the whole matrix rows and columns sum is same.
divide the matrix into parts and check every block whether there sum is same or not

In [44]:
first_block = s[0:3 ,0:3]

second_block = s[0:3 ,3:6]

third_block = s[0:3 ,6:9]
 
fourth_block = s[3:6 ,0:3]

fiveth_block = s[3:6 ,3:6]

sixth_block = s[3:6,6:9]

you will notice the pattern in the above block slicing. we will use for loop

In [45]:
#using for loop
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i : i+3, j : j+3])
        # you will se every block of 3x3 matrix is printed 
        # it took me time to understamd the slicing

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [46]:
#now summing the every block of s to see if sum is same or not 
# if same its valid otherwise not

for i in range(0,9,3):
    for j in range(0,9,3):
        sl =s[i : i+3, j : j+3]
        print(sl.sum())

45
45
45
45
45
45
45
45
45


General Question

In [47]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [48]:
#Get the shape of the matrix.
print(data.shape)

(5, 3)


In [49]:
#Find the average age of students.
average_age = np.mean(data[:,0])
print(average_age)

18.4


In [50]:
#Extract Math marks of all students.
maths_mrks = data[:,1]
print(maths_mrks)

[85 92 76 65 90]


In [51]:
#Find the highest Science mark.
max_sc_mrks = np.max(data[:,2])
print(max_sc_mrks)

95


In [52]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]


array([[19, 92, 88]])

In [53]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [54]:
print("Original data:\n", data)

# Add 5 to the second column (index 1)
data[:, 1] = data[:, 1] + 5

print("\nData after data[:, 1] = data[:, 1] + 5:\n", data)

Original data:
 [[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]

Data after data[:, 1] = data[:, 1] + 5:
 [[ 18  95  78]
 [ 19 102  88]
 [ 17  86  95]
 [ 18  75  70]
 [ 20 100  85]]


In [55]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [56]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:]) # its take out the mean of the both subject
#but we need mean subject wise
#so
np.mean(data[:,1:],axis =0)

array([91.6, 83.2])

In [57]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:,1] >= 80) & (data[:,2] >= 80) ]
# question why we can't use and

array([[ 19, 102,  88],
       [ 17,  86,  95],
       [ 20, 100,  85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0